#ifndef RTMCORE_NAMESPACE_H
#define RTMCORE_NAMESPACE_H

#define RTM_NAMESPACE RTM
#define RTM_BEGIN_NAMESPACE namespace RTM_NAMESPACE {
#define RTM_END_NAMESPACE }
#define RTM_USE_NAMESPACE using namespace RTM_NAMESPACE;
#define RTM_PREPEND_NAMESPACE(X) RTM_NAMESPACE::X

#endif // RTMCORE_NAMESPACE_H
